spring.application.name=event-management-system-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/EventManagement
spring.datasource.username=postgres
spring.datasource.password=Nirwani_29
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true